### ISSUE TITLE
Skin-pax gigablue text design request

### ISSUE THREAD

**Issue by dermay** [openmips/skin-pax#1]
Hi, I'm using the latest OpenMips 4.2 on a Gigablue Quad 800 with the Gigablue Pax skin.

Under Channel Selection, the Event description text is blue against a black background. 
This is very difficult to read. Can the description text please be changed to something with a high contrast, e.g. white or yellow?

In general, I find the text is too small in most screens. Is it possible to allow the user to increase font size in all menu options? Or in the main menus such as Channel Selection, Main Menu, Media Player?

Or is it possible to design a High Contrast Pax Skin for older eyes?

Many thanks

**Comment by arn354** [comment]
Simply increasing textsize is not possible without recoding all screens.
Enigma2 is not so dynamically like we wish. There is a certain space for written text and a line height.
If i increase textsize in general - then the text will be cut in most screens.

Yellow does not fit into the theme. I could live with a lightgrey or switch the colors of servicename and eventname.

**Comment by dermay** [comment]
Many thanks for your reply, 
Lightgrey or white would be great, 
The most important thing is that it has a high contrast to make it easier to read.

**Comment by coolsurfing** [comment]
Is there an option to add the Date information into the channel info screen together with the time ?
I like to see in one view Date and Time. Unfortunately I'm not the expert to change your skin with the OpenSkinDesigner. 

Thanks in advance.

**Comment by arn354** [comment]
https://github.com/openmips/skin-pax/issues/2
