### ISSUE TITLE
Add Date to the channel info screen

### ISSUE THREAD

**Issue by coolsurfing** [openmips/skin-pax#2]
I like this skin !!! It looks very nice.
Is there an option to add the Date information into the channel info screen together with the time ?
I like to see in one view Date and Time. Unfortunately I'm not the expert to change your  skin with the OpenSkinDesigner.

Thanks in advance.

**Comment by arn354** [comment]
https://github.com/openmips/skin-pax/blob/master/usr/share/enigma2/GigabluePax/skin.xml#L126
The band on top is a "template" which is used on all screens.
I see no place where date could be added without downsizing other elements.

**Comment by coolsurfing** [comment]
Hi arn354,

I think there is a place where you have already placed the time field, if you reduce a bit the letter size from the time. Then it should be possible to show time and date together ?

Kind Regards
